import { Inter } from 'next/font/google';
import '../globals.css';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import { AuthProvider } from '@/components/AuthContext';
import { Toaster } from 'react-hot-toast';
import Sidebar from '@/components/admin/Sidebar';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const AdminLayout = ({ children }) => {
  return (
    <div className=''>
      {/* <NavbarAdmin /> */}
      <Sidebar>{children}</Sidebar>
    </div>
  );
};

export default AdminLayout;
